"""Configuration package for GenEEG project."""

from .dataset_config import DatasetConfig
from .model_config import ModelConfig
from .training_config import TrainingConfig, SEED_VALUE

# Re-export commonly used constants for convenience
COMMON_EEG_CHANNELS = DatasetConfig.COMMON_EEG_CHANNELS
TARGET_SFREQ = DatasetConfig.TARGET_SFREQ
SEGMENT_SAMPLES = DatasetConfig.SEGMENT_SAMPLES

VAE_EPOCHS = TrainingConfig.VAE_EPOCHS
VAE_LR = TrainingConfig.VAE_LEARNING_RATE
VAE_BATCH_SIZE = TrainingConfig.VAE_BATCH_SIZE

LDM_EPOCHS = TrainingConfig.LDM_EPOCHS
LDM_LR = TrainingConfig.LDM_LEARNING_RATE
LDM_BATCH_SIZE = TrainingConfig.LDM_BATCH_SIZE
LDM_DIFFUSION_TIMESTEPS = TrainingConfig.LDM_DIFFUSION_TIMESTEPS

FINETUNE_EPOCHS = TrainingConfig.FINETUNE_EPOCHS
FINETUNE_LR = TrainingConfig.FINETUNE_LEARNING_RATE
FINETUNE_LR_FACTOR = TrainingConfig.FINETUNE_LR_FACTOR
FINETUNE_BATCH_SIZE = TrainingConfig.FINETUNE_BATCH_SIZE

EXPERIENCE_REPLAY_RATIO = TrainingConfig.EXPERIENCE_REPLAY_RATIO

VAE_BASE_CHANNELS = ModelConfig.VAE_BASE_CHANNELS
VAE_LATENT_DIM = ModelConfig.VAE_LATENT_DIM
VAE_LATENT_LENGTH = ModelConfig.VAE_LATENT_LENGTH
VAE_FEATURE_COND_DIM = ModelConfig.VAE_FEATURE_COND_DIM
VAE_LATENT_CHANNELS = ModelConfig.VAE_LATENT_CHANNELS

LDM_BASE_CHANNELS = ModelConfig.LDM_BASE_CHANNELS
LDM_LOW_FREQ_PRESERVATION_WEIGHT = TrainingConfig.LDM_LOW_FREQ_PRESERVATION_WEIGHT
LDM_MOMENT_LOSS_WEIGHT = TrainingConfig.LDM_MOMENT_LOSS_WEIGHT

NUM_CLASSES = ModelConfig.LDM_NUM_CLASSES  # Default: 3 classes

__all__ = [
    'DatasetConfig', 
    'ModelConfig', 
    'TrainingConfig',
    'SEED_VALUE',
    'COMMON_EEG_CHANNELS',
    'TARGET_SFREQ',
    'SEGMENT_SAMPLES',
    'VAE_EPOCHS',
    'VAE_LR',
    'VAE_BATCH_SIZE',
    'LDM_EPOCHS',
    'LDM_LR',
    'LDM_BATCH_SIZE',
    'LDM_DIFFUSION_TIMESTEPS',
    'FINETUNE_EPOCHS',
    'FINETUNE_LR',
    'FINETUNE_LR_FACTOR',
    'FINETUNE_BATCH_SIZE',
    'EXPERIENCE_REPLAY_RATIO',
    'VAE_BASE_CHANNELS',
    'VAE_LATENT_DIM',
    'VAE_LATENT_LENGTH',
    'VAE_FEATURE_COND_DIM',
    'VAE_LATENT_CHANNELS',
    'LDM_BASE_CHANNELS',
    'LDM_LOW_FREQ_PRESERVATION_WEIGHT',
    'LDM_MOMENT_LOSS_WEIGHT',
    'NUM_CLASSES',
]
